name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '16'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Debug USER and TOKEN
        run: |
          echo "USER: ${{ secrets.USER }}"
          echo "TOKEN: ${{ secrets.TOKEN }}"
        
      - name: Publish Java Package
        run: |
          ./gradlew publish
        env:
          USER: ${{ secrets.USER }}
          TOKEN: ${{ secrets.TOKEN }}
