name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '16'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Debug GITHUB_USERNAME and GITHUB_TOKEN
        run: |
          echo "GITHUB_USERNAME: $GITHUB_USERNAME"
          echo "GITHUB_TOKEN: $GITHUB_TOKEN"
        
      - name: Publish Java Package
        run: |
          ./gradlew publish
        env:
          USERNAME_GITHUB: ${{ secrets.USERNAME_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.PUBLISH }}
