name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Add execute permission to gradlew
        run: chmod +x gradlew
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '16'

      - name: Publish Java Package
        run: |
          ./gradlew publish
        env:
          USERNAME_GITHUB: ${{ secrets.USERNAME_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.PUBLISH }}
