name: Publish Java Package

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '16'

      - name: Publish Java Package
        uses: tactions/gradle-publish@v1
        with:
          gradle-version: '7.4'
          gradle-args: 'publish'
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH }}
